import { chromium } from '@playwright/test';
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
const errors = []; let tiles = 0;
page.on('pageerror', error => errors.push(error.message));
page.on('response', response => { if (response.url().includes('tile.openstreetmap.org') && response.ok()) tiles++; });
await page.goto('http://127.0.0.1:8787');
await page.locator('.place-card').first().waitFor({ timeout: 65_000 });
await page.evaluate(() => document.fonts.ready);
await page.screenshot({ path: 'test-results/live-desktop.png', fullPage: true });
await page.getByRole('button', { name: 'Crear mi recorrido', exact: true }).click();
await page.getByLabel('Personalizar con ChatGPT').uncheck();
await page.getByRole('button', { name: 'Encontrar mi recorrido' }).click();
await page.getByRole('button', { name: 'Iniciar recorrido', exact: true }).waitFor({ timeout: 65_000 });
await page.screenshot({ path: 'test-results/live-desktop-route.png', fullPage: true });
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: 'test-results/live-mobile-route.png', fullPage: true });
await page.locator('.mobile-nav').getByRole('button', { name: 'Mapa', exact: true }).click();
await page.screenshot({ path: 'test-results/live-mobile-map.png', fullPage: true });
console.log(JSON.stringify({ browserErrors: errors, loadedMapTiles: tiles, mobileOverflow: await page.evaluate(() => document.documentElement.scrollWidth > innerWidth) }));
await browser.close();
if (errors.length || !tiles) process.exitCode = 1;
